version: '2.0'

services:

  # Application container
  web:
    image: web
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile
    container_name: container-web
    env_file: ./build/docker/env
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "9000"
    volumes:
      - .:/var/www/html:rw
      #- ./build/docker/php.ini:/usr/local/etc/php/php.ini
      - ./build/docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./build/docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf:rw
    depends_on:
      - mysql

  # Database container incl. init script for local development
  mysql:
    image: mysql:5.7.18
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./build/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website

volumes:
  mysql-data:


